extends: strongloop
parser: babel-eslint
env: 
    browser: true
    commonjs: true
    es6: true
    jquery: true

rules: 
    no-unused-vars: off
    max-len: off
    no-undef: off
    radix: off
    eqeqeq: off
    no-sequences: off
    no-redeclare: off
    no-cond-assign: off
    strict: off
    no-inner-declarations: off
    no-native-reassign: off
    no-octal: off
    arrow-spacing: off
    indent: off
    semi: off
    keyword-spacing: off
    space-infix-ops: off
    no-trailing-spaces: off
    quotes: off
    eol-last: off
    comma-spacing: off
    no-multi-spaces: off
    spaced-comment: off
    space-before-function-paren: off
    comma-dangle: off
    key-spacing: off
    space-in-parens: off
    brace-style: off
    block-spacing: off
    one-var: off
    no-spaced-func: off
    semi-spacing: off
    no-multiple-empty-lines: off
    quote-props: off
    no-floating-decimal: off
    handle-callback-err: off
    no-unneeded-ternary: off


