// App
export const TOGGLE_DEV_TOOLS_SUCCESS = "TOGGLE_DEV_TOOLS_SUCCESS";
export const OPEN_LOCAL_FOLDER_SUCCESS = "OPEN_LOCAL_FOLDER_SUCCESS";
export const REFRESH_APP_SUCCESS = "REFRESH_APP_SUCCESS";

// Projects
export const LOAD_PROJECT_SUCCESS = "LOAD_PROJECT_SUCCESS";
export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";
export const SAVE_PROJECT_SUCCESS = "SAVE_PROJECT_SUCCESS";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const CLOSE_PROJECT_SUCCESS = "CLOSE_PROJECT_SUCCESS";

// Connections
export const LOAD_CONNECTION_SUCCESS = "LOAD_CONNECTION_SUCCESS";
export const LOAD_CONNECTIONS_SUCCESS = "LOAD_CONNECTIONS_SUCCESS";
export const SAVE_CONNECTION_SUCCESS = "SAVE_CONNECTION_SUCCESS";
export const DELETE_CONNECTION_SUCCESS = "DELETE_CONNECTION_SUCCESS";
